require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chapters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Chapter. As you add validations to Chapter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Chapter.create! valid_attributes
      get chapters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chapter = Chapter.create! valid_attributes
      get chapter_url(chapter)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chapter_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      chapter = Chapter.create! valid_attributes
      get edit_chapter_url(chapter)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chapter" do
        expect {
          post chapters_url, params: { chapter: valid_attributes }
        }.to change(Chapter, :count).by(1)
      end

      it "redirects to the created chapter" do
        post chapters_url, params: { chapter: valid_attributes }
        expect(response).to redirect_to(chapter_url(Chapter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chapter" do
        expect {
          post chapters_url, params: { chapter: invalid_attributes }
        }.to change(Chapter, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post chapters_url, params: { chapter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chapter" do
        chapter = Chapter.create! valid_attributes
        patch chapter_url(chapter), params: { chapter: new_attributes }
        chapter.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chapter" do
        chapter = Chapter.create! valid_attributes
        patch chapter_url(chapter), params: { chapter: new_attributes }
        chapter.reload
        expect(response).to redirect_to(chapter_url(chapter))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        chapter = Chapter.create! valid_attributes
        patch chapter_url(chapter), params: { chapter: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chapter" do
      chapter = Chapter.create! valid_attributes
      expect {
        delete chapter_url(chapter)
      }.to change(Chapter, :count).by(-1)
    end

    it "redirects to the chapters list" do
      chapter = Chapter.create! valid_attributes
      delete chapter_url(chapter)
      expect(response).to redirect_to(chapters_url)
    end
  end
end
